name: Build and deploy Node.js app to Azure Web App - soft

on:
  push:
    branches: [ main, local-sync-* ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present
      - name: Include web.config for Windows App Service
        run: |
          mkdir -p build
          if [ -f public/web.config ]; then cp public/web.config build/web.config; fi

      - name: Test
        run: npm test --if-present

      - name: Upload artifact for deployment (build folder)
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./deploy

      - name: Verify build output exists
        run: |
          test -d ./deploy/build || { echo "ERROR: ./deploy/build missing"; ls -la ./deploy; exit 1; }
          ls -la ./deploy/build | head -100

      - name: Zip build folder
        working-directory: ./deploy
        run: |
          cd build
          zip -qr ../build.zip .

      - name: List zip contents (debug)
        run: unzip -l ./deploy/build.zip | sed -n '1,100p'

      - name: Deploy to Azure Web App (zip)
        uses: azure/webapps-deploy@v3
        with:
          app-name: soft
          package: ./deploy/build.zip
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

