name: Deploy Soft.Geometry (FE) to Azure Web Apps

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME_SOFT_GEOMETRY }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_SOFT_GEOMETRY }}
        package: ./build
